import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/header-top/HeaderTop";
import HeaderBottom from "@/components/header-bottom/HeaderBottom";
import Footer from "@/components/footer/Footer";
import StoreProvider from "./StoreProvider";
import { store } from "@/lib/store";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider store={store}>
          <HeaderTop />
          <HeaderBottom />
          {children}
          <Footer />
          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
